# Car Price Regression with PyCaret
This notebook uses PyCaret to build a regression model for predicting car prices based on various features from the `CarPrice_Assignment.csv` dataset.

**Problem Statement:**
A Chinese automobile company wants to understand the factors affecting car prices in the US market. The goal is to model car prices using available features to help management understand pricing dynamics and inform business strategy.

**Dataset:**
- `CarPrice_Assignment.csv`: Contains various features of cars and their prices.

**Steps:**
1. Load the dataset
2. Set up PyCaret regression experiment
3. Compare models and select the best
4. Evaluate and save the best model
5. Predict car prices

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

In [2]:
# Load the dataset
data = pd.read_csv('CarPrice_Assignment.csv')
data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
# PyCaret Regression Setup
from pycaret.regression import RegressionExperiment
reg = RegressionExperiment()
reg.setup(data=data, target='price', session_id=123, normalize=True, transformation=True)

In [4]:
# Compare models and select the best
best_model = reg.compare_models()

In [ ]:
# Evaluate the best model
reg.evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [6]:
# Save the best model for future use
reg.save_model(best_model, 'best_car_price_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['car_ID', 'symboling', 'wheelbase',
                                              'carlength', 'carwidth',
                                              'carheight', 'curbweight',
                                              'enginesize', 'boreratio',
                                              'stroke', 'compressionratio',
                                              'horsepower', 'peakrpm', 'citympg',
                                              'highwaympg'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(inc...
                                                               use_cat_names=True))),
                 ('rest_encoding',
                  TransformerWrapper(include=['CarName'],
                                     transformer=TargetEncoder(cols=['CarName'],
                                                               handle_missing='return_nan'))),
                 ('transformation',
                  TransformerWrapper(transformer=PowerTransformer(standardize=False))),
                 ('normalize', TransformerWrapper(transformer=StandardScaler())),
                 ('trained_model', GradientBoostingRegressor(random_state=123))]),
 'best_car_price_model.pkl')

In [7]:
# Predict car prices on the same data (or new/unseen data)
predictions = reg.predict_model(best_model)
predictions.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,prediction_label
88,89,-1,mitsubishi mirage g4,gas,std,four,sedan,fwd,front,96.300003,...,spdi,3.17,3.46,7.5,116,5500,23,30,9279.0,9011.780403
72,73,3,buick skylark,gas,std,two,convertible,rwd,front,96.599998,...,mpfi,3.46,3.10,8.3,155,4750,16,18,35056.0,32303.355150
114,115,0,peugeot 505s turbo diesel,diesel,turbo,four,wagon,rwd,front,114.199997,...,idi,3.70,3.52,21.0,95,4150,25,25,17075.0,17259.228021
158,159,0,toyota corona,diesel,std,four,sedan,fwd,front,95.699997,...,idi,3.27,3.35,22.5,56,4500,34,36,7898.0,8415.955824
163,164,1,toyota corolla liftback,gas,std,two,sedan,rwd,front,94.500000,...,2bbl,3.19,3.03,9.0,70,4800,29,34,8058.0,7979.098467